import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import { Toaster } from 'react-hot-toast';
import { Suspense } from 'react'

const montserrat = Montserrat({
  subsets: ['latin'], // Ajuste conforme necessário, ex: 'latin-ext' para suporte estendido.
  weight: ['400', '500', '600', '700'], // Escolha os pesos que deseja.
  display: 'swap', // Melhor para SEO e UX.
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.className} antialiased`}
      >
        <Suspense>
          {children}
        </Suspense>
        <Toaster />
      </body>
    </html>
  );
}
